from enum import StrEnum


class TriggerType(StrEnum):
    HIRING_GROWTH = "HIRING_GROWTH"
    SALES_TEAM_EXPANSION = "SALES_TEAM_EXPANSION"
    FUNDING = "FUNDING"
    PRODUCT_LAUNCH = "PRODUCT_LAUNCH"
    ENTERPRISE_EXPANSION = "ENTERPRISE_EXPANSION"
    MARKET_EXPANSION = "MARKET_EXPANSION"
    NEW_OFFICE = "NEW_OFFICE"
    PRICING_CHANGE = "PRICING_CHANGE"
    NEW_INTEGRATION = "NEW_INTEGRATION"
    PARTNERSHIP = "PARTNERSHIP"
    LEADERSHIP_CHANGE = "LEADERSHIP_CHANGE"
    SALES_MOTION_CHANGE = "SALES_MOTION_CHANGE"
    GENERAL_CHANGE = "GENERAL_CHANGE"
    NO_MEANINGFUL_CHANGE = "NO_MEANINGFUL_CHANGE"


class Significance(StrEnum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class RecommendedAction(StrEnum):
    RESEARCH_ACCOUNT = "RESEARCH_ACCOUNT"
    REQUALIFY_ACCOUNT = "REQUALIFY_ACCOUNT"
    CREATE_FOLLOW_UP = "CREATE_FOLLOW_UP"
    NOTIFY_SALES = "NOTIFY_SALES"
    REVIEW_PRICING_CHANGE = "REVIEW_PRICING_CHANGE"
    NO_ACTION = "NO_ACTION"
